import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { HomePage } from '../frontend/components/HomePage'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Habi Pizza</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header className={styles.header}>
        <h1>Habi Pizza</h1>
        <Image src='/habiPizza.svg' alt='Habi Pizza' width={80} height={80} />
      </header>
      <main>
        <HomePage />
      </main>
      <footer className={styles.footer}>
        <a
          href='https://github.com/CalaoJuanPablo'
          className={styles.footer_link}
        >
          @CalaoJuanPablo
        </a>
      </footer>
    </div>
  )
}
